GuardianAvionicsWeb/Controllers/AircraftController.cs
using System;
using GA.ApplicationLayer;
using GA.Common;
using GA.DataTransfer;
using GA.DataTransfer.Classes_for_Web;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Data.Entity;
using System.Xml;
using System.Text;
using System.Web;
using NReco.VideoConverter;
using TallComponents.PDF;
using System.Drawing;
using System.IO;
using GA.DataTransfer.Classes_for_Services;
using System.Linq;
using GA.DataLayer;

namespace GuardianAvionicsWeb.Controllers
{
    /// <summary>
    /// All the Action methods for aircraft
    /// </summary>
    [HandleError(View = "Error")]
    [SessionExpireFilterAttribute]
    public class AircraftController : Controller
    {
        //public ActionResult AircraftDetails(int? aId, int? flag = 0)
        public ActionResult AircraftDetails(string aId, int? flag = 0)
        {
            //flag = 0 for user
            //flag = 1 for Admin
            try
            {
                if (string.IsNullOrEmpty(aId) || Session["ProfileId"] == null || Session["UserType"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                else
                {
                    aId = new Misc().Decrypt(aId);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Home");
            }

            ViewBag.Master = "_UserLayout.cshtml";
            if (Session["UserType"].ToString() == Enumerations.UserType.Admin.ToString() || flag == 1)
            {
                ViewBag.Master = "_Layout.cshtml";
            }

            //Validate Aircraft with user
            AircraftHelper helper = new AircraftHelper();

            ViewBag.IsAircraftProfile = "true";
            ViewBag.PageHeaderTitle = "Aircraft Profile";
            ViewBag.User = Session["UserType"].ToString();

            if (TempData["AircraftUpdateStatus"] != null)
            {
                string msg = TempData["AircraftUpdateStatus"].ToString();
                if (msg == "Success")
                {
                    ViewBag.ProfileUpdatemsg = GA.Common.ResourcrFiles.Common.Messages.UpdateProfile.ToString();
                }
                else
                {
                    ViewBag.ProfileUpdatemsg = GA.Common.ResourcrFiles.Common.Messages.ErrorWhileProcessing.ToString();
                }
                TempData["AircraftUpdateStatus"] = null;
            }
            else
            {
                ViewBag.ProfileUpdatemsg = "";
            }
            var AircraftData = new AircraftProfileModelWeb();

            // set viewbag with list of aircrafts data

            // by default set the default aircraft profile image.
            ViewBag.AircraftProfileImageSource = Constants.AircraftDefaultImage;
            int profileId = Convert.ToInt32(Session["ProfileId"]);
            var profile = new UserHelper().GetProfileDetailById(profileId);

            // aId == 0 is case of new aircraft creation
            if (Convert.ToInt32(aId) != 0)
            {
                int aircraftId = Convert.ToInt32(aId);
                Misc objMisc = new Misc();
                AircraftData = helper.GetAircraftDetails(aircraftId, profileId);
                AircraftData.aircraftSalesDetailList.ForEach(f => { f.TId = objMisc.Encrypt(f.Id.ToString()); f.Id = 0; });
                GuardianAvionicsEntities context = new GuardianAvionicsEntities();
                ViewBag.CatogaryList = context.Category.Where(x => x.IsActive == true &&x.AircraftId== aircraftId).OrderBy(x => x.Priority).ToList(); //&& x.AircraftId== aircraftId
                if (!System.IO.File.Exists(ConfigurationReader.EngineConfigXMLFilePath + @"\" + aircraftId.ToString() + ".xml"))
                {
                    ViewBag.EngineData = "No Record available for engine settings.";
                    ViewBag.IsEngineDataAvailable = false;
                }
                else
                {
                    try
                    {
                        ViewBag.EngineData = new CommonHelper().ParsePListForEngineSetting(aircraftId);
                        ViewBag.IsEngineDataAvailable = true;
                    }
                    catch (Exception exEngineData)
                    {
                        ViewBag.EngineData = GA.Common.ResourcrFiles.AircraftProfile.Messages.ErrorInEngineData.ToString(); ;
                        ViewBag.IsEngineDataAvailable = false;
                    }
                }
                ViewBag.Id = aircraftId;

                if (profile.UserMaster.UserType == Enumerations.UserType.Admin.ToString())
                {
                    AircraftData.IsOwner = true;
                }

                ViewBag.IsAircraftOwner = AircraftData.IsOwner;
                Session["IsOwner"] = AircraftData.IsOwner;
                ViewBag.AircraftComponentManufacturerList = AircraftData.AircraftComponentManufacturerList;
                ViewBag.ComponentModelList = AircraftData.ComponentModelList;
            }
            else
            {
                AircraftData = helper.GetEmptyAircraftDetail(Convert.ToInt32(Session["ProfileId"]));
                ViewBag.AircraftComponentManufacturerList = AircraftData.AircraftComponentManufacturerList;
                ViewBag.ComponentModelList = AircraftData.ComponentModelList;
                ViewBag.EngineData = "No Record available for engine settings.";
                ViewBag.IsEngineDataAvailable = false;
                ViewBag.IsAircraftOwner = false;
            }
           
            ViewBag.ProfileId = Convert.ToInt32(Session["ProfileId"]);
            return View("AircraftDetails", AircraftData);

        }

        public ActionResult DashBoardAircraftDetails(string aId, int? flag = 0)
        {
            //flag = 0 for user
            //flag = 1 for Admin
           
            try
            {
                if (string.IsNullOrEmpty(aId) || Session["ProfileId"] == null || Session["UserType"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                else
                {
                    aId = new Misc().Decrypt(aId);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Home");
            }

            ViewBag.Master = "_UserLayout.cshtml";
            if (Session["UserType"].ToString() == Enumerations.UserType.Admin.ToString() || flag == 1)
            {
                ViewBag.Master = "_Layout.cshtml";
            }

            //Validate Aircraft with user
            AircraftHelper helper = new AircraftHelper();

            ViewBag.IsAircraftProfile = "true";
            ViewBag.PageHeaderTitle = "Aircraft Profile";
            ViewBag.User = Session["UserType"].ToString();

            if (TempData["AircraftUpdateStatus"] != null)
            {
                string msg = TempData["AircraftUpdateStatus"].ToString();
                if (msg == "Success")
                {
                    ViewBag.ProfileUpdatemsg = GA.Common.ResourcrFiles.Common.Messages.UpdateProfile.ToString();
                }
                else
                {
                    ViewBag.ProfileUpdatemsg = GA.Common.ResourcrFiles.Common.Messages.ErrorWhileProcessing.ToString();
                }
                TempData["AircraftUpdateStatus"] = null;
            }
            else
            {
                ViewBag.ProfileUpdatemsg = "";
            }
            var AircraftData = new AircraftProfileModelWeb();

            // set viewbag with list of aircrafts data

            // by default set the default aircraft profile image.
            ViewBag.AircraftProfileImageSource = Constants.AircraftDefaultImage;
            GuardianAvionicsEntities context = new GuardianAvionicsEntities();
            int aircraftid= Convert.ToInt32(aId);
            int profileId = Convert.ToInt32(context.AircraftProfiles.Where(x => x.Id == aircraftid).Select(y => y.OwnerProfileId).FirstOrDefault());
            var profile = new UserHelper().GetProfileDetailById(profileId);

            // aId == 0 is case of new aircraft creation
            if (Convert.ToInt32(aId) != 0)
            {
                int aircraftId = Convert.ToInt32(aId);
                Misc objMisc = new Misc();
                AircraftData = helper.GetAircraftDetails(aircraftId, profileId);
                AircraftData.aircraftSalesDetailList.ForEach(f => { f.TId = objMisc.Encrypt(f.Id.ToString()); f.Id = 0; });
                ViewBag.CatogaryList = context.Category.Where(x => x.IsActive == true && x.AircraftId == aircraftId).OrderBy(x => x.Priority).ToList(); //&& x.AircraftId== aircraftId
                if (!System.IO.File.Exists(ConfigurationReader.EngineConfigXMLFilePath + @"\" + aircraftId.ToString() + ".xml"))
                {
                    ViewBag.EngineData = "No Record available for engine settings.";
                    ViewBag.IsEngineDataAvailable = false;
                }
                else
                {
                    try
                    {
                        ViewBag.EngineData = new CommonHelper().ParsePListForEngineSetting(aircraftId);
                        ViewBag.IsEngineDataAvailable = true;
                    }
                    catch (Exception exEngineData)
                    {
                        ViewBag.EngineData = GA.Common.ResourcrFiles.AircraftProfile.Messages.ErrorInEngineData.ToString(); ;
                        ViewBag.IsEngineDataAvailable = false;
                    }
                }
                ViewBag.Id = aircraftId;

                if (profile.UserMaster.UserType == Enumerations.UserType.Admin.ToString())
                {
                    AircraftData.IsOwner = true;
                }

                ViewBag.IsAircraftOwner = AircraftData.IsOwner;

GuardianAvionicsWeb/Controllers/CheckListController.cs
using GA.ApplicationLayer;
using GA.Common;
using GA.DataLayer;
using GA.DataTransfer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuardianAvionicsWeb.Controllers
{
    public class CheckListController : Controller
    {
        // GET: CheckList
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AircraftListofCheckList()
        {
            Session["UserAuthorization"] = new UserHelper().SetFeatureByUser(Convert.ToInt32(Session["ProfileId"]));
            if (Session["UserType"] == null || Session["ProfileId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.UserType = Session["UserType"].ToString();
            Misc objMisc = new Misc();
            Session["UserName"] = new UserHelper().GetUserNameByProfileId(Convert.ToInt32(Session["ProfileId"]));
            ViewBag.PageHeaderTitle = "Aircraft List";
            AircraftHelper helper = new AircraftHelper();
            //List<AircraftDetail> response = (List<AircraftDetail>)helper.setViewBagAircraftListing(Convert.ToInt32(Session["ProfileId"]));
            //response.ForEach(f => { f.TId = objMisc.Encrypt(f.Id.ToString()); f.Id = 0; });
            var response = helper.GetAircraftList(Convert.ToInt32(Session["ProfileId"]));
            int sno = 1;
            response.OrderByDescending(o => o.AircraftId).ToList().ForEach(f => { f.TId = objMisc.Encrypt(f.AircraftId.ToString()); f.SNO = sno++; });
            ViewBag.ProfileId = Convert.ToInt32(Session["ProfileId"]);
            var isCurrSubscriptionIsPlan5AndActive = new SubscriptionHelper().IsCurrSubscriptionIsPlan5AndActive(Convert.ToInt32(Session["ProfileId"]));
            if (!isCurrSubscriptionIsPlan5AndActive && Session["UserType"].ToString() != Enumerations.UserType.Maintenance.ToString())
            {
                sno = 1;
                int aircraftId = helper.GetFirstAircraftRegisteredByProfileId(Convert.ToInt32(Session["ProfileId"]));
                response.Where(w => w.AircraftId != aircraftId).ToList().ForEach(f => { f.AircraftId = 0; f.TId = null; });
                response.OrderByDescending(o => o.TId).ToList().ForEach(f => f.SNO = sno++);
            }
            return View("AircraftListofCheckList", response);
        }
        public ActionResult CheckList(string aId, int? flag = 0)
        {
            try
            {
                
                if (string.IsNullOrEmpty(aId) || Session["ProfileId"] == null || Session["UserType"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                else
                {
                    aId = new Misc().Decrypt(aId);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Login", "Home");
            }
            var AircraftData = new AircraftProfileModelWeb();
            ViewBag.Master = "_UserLayout.cshtml";
            if (Session["UserType"].ToString() == Enumerations.UserType.Admin.ToString() || flag == 1)
            {
                ViewBag.Master = "_Layout.cshtml";
            }

            //Validate Aircraft with user
            ViewBag.User = Session["UserType"].ToString();

            
            int profileId = Convert.ToInt32(Session["ProfileId"]);
            var profile = new UserHelper().GetProfileDetailById(profileId);

            // aId == 0 is case of new aircraft creation
            if (Convert.ToInt32(aId) != 0)
            {
                int aircraftId = Convert.ToInt32(aId);
                Misc objMisc = new Misc();
                AircraftHelper helper = new AircraftHelper();
                AircraftData = helper.GetAircraftDetails(aircraftId, profileId);
                GuardianAvionicsEntities context = new GuardianAvionicsEntities();
                ViewBag.CatogaryList = context.Category.Where(x => x.IsActive == true && x.AircraftId == aircraftId).OrderBy(x => x.Priority).ToList(); //&& x.AircraftId== aircraftId
                ViewBag.Id = aircraftId;

                if (profile.UserMaster.UserType == Enumerations.UserType.Admin.ToString())
                {
                    AircraftData.IsOwner = true;
                   
                }
                
                Session["IsOwner"] = AircraftData.IsOwner;
                

            }
            ViewBag.ProfileId = Convert.ToInt32(Session["ProfileId"]);
            return View("CheckList");
        }
    }
}

GuardianAvionicsWeb/Views/CheckList/AircraftListofCheckList.cshtml
@model List<GA.DataTransfer.Classes_for_Web.AircraftSummary>
@using GA.Common;
@{
    ViewBag.Title = "AircraftList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var userType = Session["UserType"] as string;
}



<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/js/jquery.js"></script>
<script src="~/js/bootbox.js"></script>

<script type="text/javascript">
    $(document).ready(function (e) {
        $("#hdnProfileId").val(@ViewBag.ProfileId)
        $("#txtSearch").bind("keyup", function (e) {
            var str = this.value;
            if (str == '') {
                $('.col-md-55').each(function (index, value) {
                    $(this).show();
                });
            }
            else {
                $('.col-md-55').each(function (index, value) {

                    if ($(this).attr('id').indexOf(str) != -1) {
                        $(this).show();
                    }
                    else {
                        $(this).hide();
                    }
                });
            }
        });

        $('input[type=radio][name=rbtnView]').change(function () {
            if (this.value == 'Image') {
                $('#divAircraftImageView').show();
                $('#divAircraftTableView').hide();
            }
            else   {
                $('#divAircraftImageView').hide();
                $('#divAircraftTableView').show();
            }
        });
        //var table = $('#datatable-fixed-header, #datatable-fixed-header1').DataTable({
        //    fixedHeader: true
        //});
        var table = $('#datatable-fixed-header, #datatable-fixed-header1').DataTable();

    });

    function DeleteAircraft(aId) {
        bootbox.confirm("@GA.Common.ResourcrFiles.AircraftProfile.Messages.ConfirmDeleteAircraft.ToString()", function (result) {
            if (result) {
                $.post("/IMounts/Aircraft/DeleteAircraft", {
                    aircraftId: aId,
                    profileId: $("#hdnProfileId").val()
                },
                       function (data) {
                           $("#divAircraftList").html(data);
                           $('#datatable-fixed-header').dataTable();
                           bootbox.alert('@GA.Common.ResourcrFiles.AircraftProfile.Messages.DeleteAircraft.ToString()', function () {
                           });
                           ga('send', 'event', 'Button', 'Click', 'DeleteAircraftProfile');

                       });
            }
        });
    }

    function subMsg() {
        bootbox.alert('To view aircraft details, you have to purchase subscription plan 5', function () {
        });
    }
</script>


<input id="hdnProfileId" type="hidden" value="" />

<div id="divRadioOption" class="col-md-12 col-sm-12 no-padding margintop20" style="text-align:center">
    <input type="radio" value="Image" name="rbtnView" checked /> &nbsp;<b> Image View </b>&nbsp;&nbsp;&nbsp;
    <input type="radio" value="Table" name="rbtnView" />&nbsp;<b> List View </b>
</div>

@if (userType != Enumerations.UserType.DemoUser.ToString())
{
    <div id="divAircraftTableView" class="col-md-12 col-sm-12 no-padding margintop20" style="display:none">
        <div class="x_panel clearfix">
            <div id="divAircraftList">
                @Html.Partial("_AircraftListPartial", Model)
            </div>
        </div>
    </div>

    <div id="divAircraftImageView" class="col-md-12 no-padding margintop20">
        <div class="x_panel clearfix">
            <div class="x_title clearfix">
                <div class="col-sm-6"></div><div class="col-sm-6 form-inline text-right">Search : <input type="text" class="form-control input-sm" id="txtSearch" /></div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row">
                    @foreach (var aircraft in Model.OrderBy(o => o.SNO))
                    {
                        <div class="col-md-55" id='@aircraft.aircraftNNumber'>
                            <div class="thumbnail">
                                <div class="image view view-first">
                                    @if (aircraft.TId != null)
                                    {
                                        <a href='@Url.Action("CheckList", "CheckList", new { aid = aircraft.TId })'>  <img style="width: 100%; display: block;" src='@aircraft.aircraftImage' alt="image" /></a>
                                    }
                                    else
                                    {
                                        <a onclick="subMsg();" style="cursor:pointer">  <img style="width: 100%; display: block;" src='@aircraft.aircraftImage' alt="image" /></a>
                                    }
                                </div>
                                <div class="caption">
                                    <p><strong>Aircraft Type</strong> : @aircraft.aircraftType</p>
                                    <p class="textellipsis"><strong>Aircraft Tail No.</strong> : <span class="textellipsis">@aircraft.aircraftNNumber</span></p>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

}
else
{
    <div id="divAircraftTableView" class="col-md-12 no-padding margintop20" style="display:none">
        <div class="x_panel clearfix">
            <div id="divAircraftList">
                <table id="datatable-fixed-header" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Sno</th>
                            <th>Aircraft Listing</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="display:none">1</td>
                            <td>Demo</td>
                            <td><a class="btn btn-primary btn-xs" href="@Url.Action("AircraftDetails", "Aircraft", new { aid = 0})"><i class="fa fa-search-plus"></i> View Details</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="divAircraftImageView" class="col-md-12 no-padding margintop20">
        <div class="x_panel clearfix">
            <div class="x_title clearfix">
                <div class="col-sm-6"></div><div class="col-sm-6 form-inline text-right">Search : <input type="text" class="form-control input-sm" id="txtSearch" /></div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row">

                    <div class="col-md-55">
                        <div class="thumbnail">
                            <div class="image view view-first">

                                <a href='@Url.Action("AircraftDetails", "Aircraft", new { aid = "Ej3uds0n4IAbWdEzJ+CPsw=="})'>  <img style="width: 100%; display: block;" src='../Images/GA/profile_pic.png' alt="image" /></a>

                            </div>
                            <div class="caption">
                                <p><strong>Aircraft Type</strong> : Demo</p>
                                <p class="textellipsis"><strong>Aircraft Tail No.</strong> : <span class="textellipsis">Demo</span></p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}